const excluded = [
    "Contact us",
    "External Documentation Sites",
    "Getting Started",
    "Overview",
    "Example implementation",
    "Example",
    "Privacy",
    "Redundancy",
    "Marketplace",
    "Summary",
    "How Does it Work?",
    "Snippet I: Testing Hello NEAR",
    "Snippet II: Testing Donations",
    "Snippet I: Testing a Counter",
    "Snippet II: Modifying the Context",
    "Prerequisites",
    "Testing",
    "Resources",
    "Other Documentation Pages",
    "Starting the Counter",
    "Interacting With Hello NEAR",
    "Introduction"
];

const headers = {
    "Deploying a Contract": "How to deploy a contract?",
    "Upgrading a Contract": "How to upgrade a contract?",
    "Migrating Contract's State": "How to migrate a contract?",
    "Locking a Contract": "How to lock a contract?",
    "Implicit Accounts": "What is implicit account?",
    "Named Accounts": "What is named account?",
    "1 `signerId`": "What is signerId?",
    "2 `signerPublicKey`": "What is signerPublicKey?",
    "3 `receiverId`": "What is receiverId`?",
    "4 `nonceForPublicKey`": "What is nonceForPublicKey?",
    "5 `actions`": "What are actions?",
    "6 `blockHash`": "What is blockHash?",
    "Benefits of Access Keys": "What are benefits of Access Keys?",
    "Function Call Keys": "What is Function Call Key?",
    "Locked Accounts": "What is locked account?",
    "Users": "What users can do?",
    "Validators": "Who are validators?",
    "Loss of FullAccess key": "What Loss of FullAccess key means?",
    "Loss of FunctionCall access key": "What Loss of FunctionCall access key means?",
    "Refunding deleted accounts": "How deleted accounts are getting refunding?",
    "Deleting account with non-existent beneficiary": "Is it possible to delete account with non-existent beneficiary?",
    "Account with zero balance is garbage-collected, just before it receives refund": "What if account with zero balance is garbage-collected, just before it receives refund?",
    "Thinking in gas": "What is gas?",
    "Attach extra gas; get refunded!": "How extra attached gas is getting refunded?",
    "Mining your transaction": "How to mine your transaction on Arweave?",
    "Retrieve the image": "How to Retrieve the image on Arweave?",
    "Integration example": "What is the IPFS Integration example?",
    "IPFS": "What is the IPFS?",
    "btw, you can remove data to unstake some tokens": "How to remove data to unstake some tokens?",
    "Starting Hello NEAR": "How to start building on NEAR?",
    "Creating a Fungible Token": "How to create a Fungible Token?",
    "Querying Metadata": "How to query FT metadata?",
    "Registering a User": "How to register a User in FT?",
    "Getting Balance": "Hot to get FT balance?",
    "Attaching FTs to a Call": "How to attach FT to a Call?",
    "Minting an NFT": "How to mint an NFT?",
    "Minting Collections": "How to mint an NFT collections?",
    "Royalties": "What are NFT royalties?",
    "Approving Users": "How to approve users in NFT contact?",
    "Transferring an NFT": "How to transfer an NFT?",
    "Attaching NFTs to a Call": "How to attach NFTs to a Call?",
    "Events": "How to track events?",
    "Sandbox Testing": "How to test in a sandbox?",
    "Patch State on the Fly": "How to patch State on the Fly in a sandbox?",
    "Time Traveling": "What is the Time Traveling in a sandbox",
    "Launch Kurtosis NEAR Module": "How to launch Kurtosis NEAR Module?",
};

module.exports = {headers, excluded};